name: Dispatch
on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - uses: actions/github-script@v7
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          script: |
            const script = await import('${{ github.workspace }}/src/index.js');
            await script({ APP_ID: process.env.APP_ID, PRIVATE_KEY: process.env.PRIVATE_KEY });
